[package]
name = "alarmmgr-bin"
version = "0.0.1"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/alarmmgr"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/alarmmgr"
homepage = "https://github.com/darwinia-network/alarmmgr"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[[bin]]
name = "alarmmgr"
path = "src/main.rs"

[dependencies]
tracing    = "0.1"
color-eyre = "0.6"

sentry     = "0.27"
structopt  = "0.3"
colored    = "2"
term-table = "1.3"

strum = { version = "0.21", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
