name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
#  pull_request:
#    branches: [main]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:

  release-alarmmgr:
    name: Release alarmmgr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - uses: benjlevesque/short-sha@v1.2
      - uses: olegtarasov/get-tag@v2.1

      - name: Build docker image
        run: |
          BASE_PATH=$(pwd)
          IMAGE_NAME=${{ env.DOCKER_REGISTRY }}/${{ github.repository }}
          IMAGE_SHA=${IMAGE_NAME}:sha-${SHA}
          IMAGE_TAG=${IMAGE_NAME}:${GIT_TAG_NAME}

          docker build \
            -f ${BASE_PATH}/Dockerfile \
            -t ${IMAGE_SHA} \
            ${GIT_TAG_NAME:+-t $IMAGE_TAG} \
            .
          docker push ${IMAGE_SHA}
          if [ -n "${GIT_TAG_NAME}" ]; then
            docker push ${IMAGE_TAG}
          fi
